### ISSUE TITLE
front page example is not reproducible

### ISSUE THREAD

**Issue by fmv1992** [mpcabd/python-arabic-reshaper#19]
Hello,

Thanks for this package.

The example on the front page is not reproducible, even after:

    pip3 install --upgrade arabic-reshaper bidi
    pip3 install python-bidi

Please provide a minimal working example for us to better use this program.

Best,

**Comment by ravarage** [comment]
pip3 install python-bidi
bidi.algorithm import get_display

**Comment by mpcabd** [comment]
@ravarage's comment is correct, but also I pushed commit 1175907 which solves this for you.
