### ISSUE TITLE
Custom harakat postion

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [mpcabd/python-arabic-reshaper#21]
Hi, is it possible to set custom harakat position, when I use ZekrQuran font the harakat are positioned really high or is possible to hide Arabic letters so that I can redraw the letters twice one for the Harakat and the other for the letters with custom text position

![imagedraw](https://user-images.githubusercontent.com/7900956/40988141-44e47f90-68e2-11e8-868a-cf0ec8fab7a4.png)

```
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import unittest
import sys
from arabic_reshaper import ArabicReshaper
from bidi.algorithm import get_display
from PIL import Image, ImageFont, ImageDraw, ImageEnhance

# text_to_be_reshaped = 'اللغة العربية رائعة'
text_to_be_reshaped = u"إِيَّاكَ نَعۡبُدُ وَإِيَّاكَ نَسۡتَعِينُ"


configuration = {
    'delete_harakat': False,
    'delete_tatweel': False,
    'support_ligatures': True,
    'support_zwj': True,
    'shift_harakat_position': False,
    'use_unshaped_instead_of_isolated': False
}
reshaper = ArabicReshaper(configuration=configuration)

reshaped_text = reshaper.reshape(text_to_be_reshaped)
font = ImageFont.truetype("/Users/aal29/Github/Personal/gq-tool/ZekrQuran.ttf", 50)

bidi_text = get_display(reshaped_text)

image = Image.new('RGBA', (500,500), "black")
image_draw = ImageDraw.Draw(image)
image_draw.text((50,50), bidi_text, fill=(255,255,255,128), font=font)
# image_draw.text((50,75), bidi_text, fill=(255,255,255,128), font=font)
image.save("ImageDraw.png")
```

**Comment by mpcabd** [comment]
It's outside the scope of the tool, the tool works on strings, it is not concerned with the rendering engine you use or what font you use with what options.

I suggest you check what options you can use with `Image.text` and see if you can setup a `line-height` like what's in CSS.

The reshaper only shuffles characters and changes them from a form to another, it doesn't do anything else.

**Comment by Ashraf-Ali-aa** [comment]
thanks for the suggestion

**Comment by mrashidmgr** [comment]
Great Thanks Mr. Ashraf-Ali-aa. for your python code.

**Comment by imamcs19** [comment]
Hi All, Let's me share the great solution for  solved "Custom harakat postion" using PIL 

from PIL import Image, ImageDraw, ImageFont

# Function to split text into lines based on max width
def wrap_text(draw, text, font, max_width):
    # Split the text by space or punctuation marks to handle phrases properly
    words = text.split(' ')
    
    lines = []
    current_line = []
    
    for word in words:
        # Form a trial line
        trial_line = ' '.join(current_line + [word])
        
        # Calculate the width of the trial line using textbbox (returns a bounding box)
        bbox = draw.textbbox((0, 0), trial_line, font=font)
        width = bbox[2] - bbox[0]  # bbox[2] is right, bbox[0] is left
        
        # If the trial line width exceeds max_width, finalize the current line and start a new one
        if width > max_width and current_line:
            lines.append(' '.join(current_line))
            current_line = [word]
        else:
            current_line.append(word)
    
    # Add the last line
    if current_line:
        lines.append(' '.join(current_line))
    
    return lines

# Function to calculate image size and text position based on screen size
def calculate_image_and_text_position(screen_width, screen_height, padding=20):
    # Set image size to be a percentage of the screen size
    image_width = int(screen_width * 0.8)
    image_height = int(screen_height * 0.6)
    
    # Set text position to have some padding from the top left corner
    text_position = (padding, padding)

    return (image_width, image_height), text_position

# Function to calculate text's horizontal position based on alignment
def calculate_text_position(alignment, image_width, line_width, padding):
    if alignment == 'left':
        return padding  # Text starts from the left with padding
    elif alignment == 'center':
        return (image_width - line_width) // 2  # Center the text horizontally
    elif alignment == 'right':
        return image_width - line_width - padding  # Text starts from the right with padding
    else:
        raise ValueError("Invalid alignment option. Choose 'left', 'center', or 'right'.")

# Function to generate image with RTL text support, shadow, and alignment
def generate_image(text, font_path, output_image_path, screen_size, alignment='right', shadow_color=(128, 128, 128), shadow_thickness=3, padding=20):
    # Calculate image size and text position based on screen size
    image_size, text_position = calculate_image_and_text_position(screen_size[0], screen_size[1], padding)
    
    # Create a blank image with transparent background (RGBA mode)
    image = Image.new('RGBA', image_size, (0, 0, 0, 0))  # (0,0,0,0) is fully transparent
    draw = ImageDraw.Draw(image)

    # Load the custom font
    try:
        font = ImageFont.truetype(font_path, 50)
    except IOError:
        print(f"Font at {font_path} not found.")
        return

    # Define the max width for wrapping text
    max_width = image_size[0] - 2 * padding  # To account for padding

    # Split the Arabic text into wrapped lines
    wrapped_text = wrap_text(draw, text, font, max_width)

    # Initial text position (Y position)
    y_offset = text_position[1]  # Start from the top based on padding

    for line in wrapped_text:
        # Calculate the line width for alignment purposes
        bbox = draw.textbbox((0, 0), line, font=font)
        line_width = bbox[2] - bbox[0]  # Width of the line
        
        # Calculate the X position based on the alignment
        x_offset = calculate_text_position(alignment, image_size[0], line_width, padding)
        
        # Define text position and set alignment
        line_position = (x_offset, y_offset)

        # Draw shadow by offsetting the text position slightly multiple times
        shadow_offset_positions = [(line_position[0] + i, line_position[1] + i) for i in range(1, shadow_thickness + 1)]

        for offset_position in shadow_offset_positions:
            draw.text(offset_position, line, font=font, fill=shadow_color, direction='rtl')

        # Draw the main text on top of the shadow with a different color
        draw.text(line_position, line, font=font, fill=(255, 255, 255), direction='rtl')  # White text

        # Move Y position down for the next line
        y_offset += 120  # Adjust line spacing based on your preference

    # Save the image
    image.save(output_image_path)
    print(f"Image saved to {output_image_path}")

# Path to the custom font (make sure it exists on your system)
# font_path ="/Users/imamcs/Library/Fonts/Tajawal-Regular.ttf"
# font_path="/Users/imamcs/Library/Fonts/traditional-arabic.ttf"
# font_path="/Users/imamcs/Library/Fonts/Amiri-Regular.ttf"
# font_path="/Users/imamcs/Library/Fonts/LPMQ IsepMisbah.ttf"
font_path="/Users/imamcs/Library/Fonts/ZekrQuran.ttf" # => look good 


# Arabic text to render
# arabic_text = "يَكَادُ الْبَرْقُ يَخْطَفُ اَبْصَارَهُمْ ۗ كُلَّمَآ اَضَاۤءَ لَهُمْ مَّشَوْا فِيْهِ ۙ وَاِذَآ اَظْلَمَ عَلَيْهِمْ قَامُوْا ۗوَلَوْ شَاۤءَ اللّٰهُ لَذَهَبَ بِسَمْعِهِمْ وَاَبْصَارِهِمْ ۗ اِنَّ اللّٰهَ عَلٰى كُلِّ شَيْءٍ قَدِيْرٌ ࣖ"
# arabic_text = "۞ اِنَّ اللّٰهَ لَا يَسْتَحْيٖٓ اَنْ يَّضْرِبَ مَثَلًا مَّا بَعُوْضَةً فَمَا فَوْقَهَا ۗ فَاَمَّا الَّذِيْنَ اٰمَنُوْا فَيَعْلَمُوْنَ اَنَّهُ الْحَقُّ مِنْ رَّبِّهِمْ ۚ وَاَمَّا الَّذِيْنَ كَفَرُوْا فَيَقُوْلُوْنَ مَاذَآ اَرَادَ اللّٰهُ بِهٰذَا مَثَلًا ۘ يُضِلُّ بِهٖ كَثِيْرًا وَّيَهْدِيْ بِهٖ كَثِيْرًا ۗ وَمَا يُضِلُّ بِهٖٓ اِلَّا الْفٰسِقِيْنَۙ"
text_to_be_reshaped = "إِيَّاكَ نَعۡبُدُ وَإِيَّاكَ نَسۡتَعِينُ"
arabic_text = text_to_be_reshaped

# User's screen size (example: 1920x1080
# )
screen_size = (1920, 1080)

# Generate image with alignment option (choose 'left', 'center', or 'right')
generate_image(arabic_text, font_path, 'temp/output-arabic-aligned_3.png', screen_size, alignment='center', shadow_color=(50, 50, 50), shadow_thickness=5)
![output-arabic-aligned_3](https://github.com/user-attachments/assets/ffb23c3a-0c6c-4c1b-bfb1-e70038dd7a8a)
