### ISSUE TITLE
How can we handle such case?

### ISSUE THREAD

**Issue by navenduagarwal** [mpcabd/python-arabic-reshaper#22]
original text : علامات المحبة

![1](https://user-images.githubusercontent.com/4066092/41147362-d696a0f6-6b23-11e8-8419-0df1ba4d32ed.JPG)

My code is below:

```
from PIL import ImageFont, ImageDraw, Image
import arabic_reshaper
from bidi.algorithm import get_display

def create_text_image(base_image_path=settings.MEDIA_ROOT + '/creative/a1.jpg',
                      output_image_path=settings.MEDIA_ROOT + '/images/output.jpg', text_start_height=820,
                      font_size=40, text_color="#ffffff", text_arabic='', text_english=''):
    # Load & Draw Image
    image = Image.open(base_image_path)
    draw = ImageDraw.Draw(image)
    print('Hello')
    # use a truetype font
    reshaped_text = arabic_reshaper.reshape(text_arabic)
    bidi_text = get_display(reshaped_text)
    font = ImageFont.truetype(settings.MEDIA_ROOT + 'fonts/regular.ttf', font_size)

    # prepare text
    iw, ih = image.size
    w_a, h_a = font.getsize(bidi_text)
    w_e, h_e = font.getsize(text_english)
    textX_a = int((iw - w_a) / 2)
    textX_e = int((iw - w_e) / 2)

    draw.text((textX_a, text_start_height), bidi_text, font=font, fill=text_color)
    draw.text((textX_e, text_start_height+h_a+10), text_english, font=font, fill=text_color)

    image.save(output_image_path)
```

Thanks in advance. Pillow rtl is not working, so I am stuck :(

**Comment by ravarage** [comment]
my code as below show up fine , its font related issue 
> 
> from PIL import ImageFont, ImageDraw, Image
> import arabic_reshaper
> from bidi.algorithm import get_display
> 
> image = Image.new('RGB', (200, 200), color='White')
> draw = ImageDraw.Draw(image)
> 
> # use a truetype font
> reshaped_text = arabic_reshaper.reshape('علامات المحبة')
> bidi_text = get_display(reshaped_text)
> font = ImageFont.truetype(font='arial.ttf', size=30)
> 
> draw.text((0, 0), bidi_text,font=font, fill=(0,0,0,0))
> 
> 
> image.show()

**Comment by mpcabd** [comment]
Like @ravarage said it's purely a font issue, use Arial like suggested, or try one of [Google's fonts](https://fonts.google.com/?subset=arabic), to my knowledge those fonts have support for all characters, I might be mistaken though, only by testing you'd find out.

See my [comment here](https://github.com/mpcabd/python-arabic-reshaper/issues/20#issuecomment-394168744) on issue #20 for a similar case
