### ISSUE TITLE
Tashkeel(Harakat) Rendering Problem

### ISSUE THREAD

**Issue by abdallah-Nasser** [mpcabd/python-arabic-reshaper#32]
Tashkeel overlaps with characters and with other tashkeel 
![Tashkeel_problem](https://user-images.githubusercontent.com/51908088/59593872-06613f80-90f3-11e9-9929-47557377f721.jpg)
Note I am using Pil to draw that text on the image

**Comment by DeepInSearch** [comment]
In arabic AcTiv dataset,  some letters are combined with Tashkeel, and represented in a new label, how to know the right unicode? Example: 
`
<Image id="AljazeeraHD_vd01_frame_208-1">
 <ArabicTranscription>مسيرات في الإسكندرية ضد الانقلاب وهتافات تعبّر</ArabicTranscription>
 <LatinTranscription>Miim_B Siin_M Yaa_M Raa_E Alif_I Taaa_I Space Faa_B Yaa_E Space Alif_I Laam_IHamzaUnderAlif_I Siin_B Kaaf_M Nuun_M Daal_E Raa_I Yaa_B TaaaClosed_E Space Daad_B Daal_E Space Alif_I Laam_EAlif_E Nuun_B Gaaf_M Laam_EAlif_E Baa_I Space Waaw_I Haa_B Taaa_M Alif_E Faa_B Alif_E Taaa_I Space Taaa_B Ayn_M BaaChadda_M Raa_I</LatinTranscription>
</Image>
`

**Comment by mpcabd** [comment]
This is a rendering problem, not a reshaping problem.
Try different fonts, try different font-sizes, letter heights, etc.

The reshaper uses the standard [Unicode](https://en.wikipedia.org/wiki/Arabic_script_in_Unicode) symbols for all the characters and tashkeel. There are no special symbols for letters with tashkeel on them, tashkeel symbols have no width so they should be rendered over the previous character.
