### ISSUE TITLE
How I can undo reshaped text?

### ISSUE THREAD

**Issue by mohsenjavidpanah** [mpcabd/python-arabic-reshaper#34]
Hi

I used this library for many use but now i need to undo reshaped text to original format, I do some search and i can't find any snippet about this action, This library have any function/class for undo reshaped arabic text?

Thank you for this great library

**Comment by mpcabd** [comment]
Hi, 

No unfortunately, this library doesn't undo the reshaping, could be an improvement point. Feel free to submit an MR if you could do it 😊
