### ISSUE TITLE
Enabling harakat breaks everything

### ISSUE THREAD

**Issue by MicleBrick** [mpcabd/python-arabic-reshaper#35]
Without harakaat:
![image](https://user-images.githubusercontent.com/6323125/62487806-c3d1f000-b790-11e9-9768-55673c5eb9bf.png)
With harakat:
![image](https://user-images.githubusercontent.com/6323125/62487812-cb919480-b790-11e9-80f3-f1a7238aaac7.png)

**Comment by mpcabd** [comment]
Hi @m-macaskill,

What font are you using? What rendering system are you using to render those images? I suspect it's one of those that's breaking things for you, as the reshaper itself doesn't have a problem with Harakat, and maps them properly, but then it's all up to the font and rendering system to do their job perfectly.

**Comment by MicleBrick** [comment]
Andalus font, and using Pillow. I managed to get it working using Java AWT and the reshaper this is based on. It still doesn't look as good in either program as it does in Microsoft word though. Do you know of a better rendering system?

**Comment by mpcabd** [comment]
Unfortunately I am not aware of other systems for Python, but if your end result is just images, you can maybe use selenium to generate HTML/SVG pages that a browser can display, then grab the rendered output from the browser and save it.
