### ISSUE TITLE
arabic_reshaper/__version__.py filenotfound error 

### ISSUE THREAD

**Issue by amzatha** [mpcabd/python-arabic-reshaper#40]
Asalamu Alaikum.

Thanks for the wonderful package. I am trying to use your package in a small apk to show details of quran verses when surah number is given. When i run in python, it is working fine. When i build the apk(builozer), and ran the app in mobile, it crashed with below error. I got the error from ADB logs.

05-12 17:07:57.625 20960 21128 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.pynew.pynew/files/app/.kivy/logs/kivy_20-05-12_0.txt
05-12 17:07:57.625 20960 21128 I python  : [INFO   ] [Kivy        ] v1.11.1
05-12 17:07:57.625 20960 21128 I python  : [INFO   ] [Kivy        ] Installed at "/data/user/0/org.pynew.pynew/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
05-12 17:07:57.625 20960 21128 I python  : [INFO   ] [Python      ] v3.8.1 (default, May 12 2020, 02:14:46) 
05-12 17:07:57.625 20960 21128 I python  : [Clang 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec7462
05-12 17:07:57.625 20960 21128 I python  : [INFO   ] [Python      ] Interpreter at ""
05-12 17:07:58.226 20960 21128 I python  : [INFO   ] [Factory     ] 184 symbols loaded
05-12 17:07:58.471 20960 21128 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
05-12 17:07:58.506 20960 21128 I python  : [INFO   ] [Text        ] Provider: sdl2
05-12 17:07:58.857 20960 21128 I python  :  Traceback (most recent call last):
05-12 17:07:58.857 20960 21128 I python  :    File "/home/kivy/pynew/.buildozer/android/app/main.py", line 11, in <module>
05-12 17:07:58.858 20960 21128 I python  :    File "/home/kivy/pynew/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/pynew/arabic_reshaper/__init__.py", line 6, in <module>
05-12 17:07:58.859 20960 21128 I python  :  FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/org.pynew.pynew/files/app/_python_bundle/site-packages/arabic_reshaper/__version__.py'
05-12 17:07:58.859 20960 21128 I python  : Python for android ended.

Can you please help to fix this issue?

**Comment by mpcabd** [comment]
I'm sorry I just noticed this issue, have you got an update on it? were you able to solve it? I couldn't reproduce it as I don't have the environment setup for kivy and buildozer, maybe you can share a Docker image that shows the problem?
