### ISSUE TITLE
"Arabic typesetting" font doesn't draw letters properly [as shown].

### ISSUE THREAD

**Issue by ahmed4end** [mpcabd/python-arabic-reshaper#41]
the font "Arabic typesetting" does work with the arabic reshaper library as expected it shows instead [a question mark] replacing many letters that ruins the afterall result and here is an example of drawing random Arabic words like "أمتحان رياضيات".
and if i used the option "use_unshaped_instead_of_isolated " it corrects some letters and damage another letters i wonder if there is a way to get around this issue cuz this font if really famous one in the arabic fonts !
[https://ibb.co/m6Y1VRh](url)

**Comment by mpcabd** [comment]
Can you show me how you're using the config mentioned? I suspect it's not being used or utilised correctly.


This image show the text you provided while enabling `use_unshaped_instead_of_isolated`


![image](https://user-images.githubusercontent.com/644992/85140123-1d29fd00-b245-11ea-88b4-580c906a71fa.png)

**Comment by ahmed4end** [comment]
![image](https://user-images.githubusercontent.com/35382418/85222448-55534c00-b3bb-11ea-8db2-0a2002fcec60.png)
here is a snippet of how i used the "use_unshaped_instead_of_isolated" option and i wish i'm wrong at using it.
and this is the result of me code : 
![image](https://user-images.githubusercontent.com/35382418/85222466-80d63680-b3bb-11ea-8059-c3c5e336ff0a.png)

**Comment by mpcabd** [comment]
I can't seem to reproduce it, maybe the font file you're using is not properly configured, have you tried using a TrueType® (.ttf) file?

```python
import arabic_reshaper
import os

from PIL import Image, ImageDraw, ImageFont
from bidi.algorithm import get_display

directory = os.path.abspath(os.path.dirname(__file__))


def f(p): return os.path.join(directory, p)


text_to_be_reshaped = 'امتحان الرياضيات النهائي'
reshaper = arabic_reshaper.ArabicReshaper({
    'use_unshaped_instead_of_isolated': True
})
reshaped_text = reshaper.reshape(text_to_be_reshaped)
bidi_text = get_display(reshaped_text)

font = ImageFont.truetype(f('arabic-typesetting.ttf'), 120)
image = Image.new('RGBA', (800, 600), (255, 255, 255, 255))
image_draw = ImageDraw.Draw(image)
image_draw.text((10, 10), bidi_text, fill=(0, 0, 0, 255), font=font)
image.save(f('text-manual-config.png'))

config_from_font = arabic_reshaper.config_for_true_type_font(
    f('arabic-typesetting.ttf'))
reshaper = arabic_reshaper.ArabicReshaper(config_from_font)
reshaped_text = reshaper.reshape(text_to_be_reshaped)
bidi_text = get_display(reshaped_text)
image_draw.rectangle([0, 0, 800, 600], fill=(255, 255, 255, 255))
image_draw.text((10, 10), bidi_text, fill=(0, 0, 0, 255), font=font)
image.save(f('text-auto-config.png'))
```

---

Manual Config: 
![image](https://user-images.githubusercontent.com/644992/85943077-f7c87d80-b92d-11ea-9378-d7e510ebc1a9.png)

---

Auto Config: 
![image](https://user-images.githubusercontent.com/644992/85943088-04e56c80-b92e-11ea-9eff-69267ba3b83e.png)

---

The code is using my latest release `2.1.0` which has a new method to read a `.ttf` file and configure the reshaper accordingly. See [this new section in the README](https://github.com/mpcabd/python-arabic-reshaper#settings-based-on-a-truetype-font) for more info.

**Comment by ahmed4end** [comment]
@mpcabd  i did upgrade the library and tried your code and amazingly solved my problems and worked  smoothly, i'm very grateful, thanks.
