### ISSUE TITLE
A new feature that should be added.

### ISSUE THREAD

**Issue by ahmed4end** [mpcabd/python-arabic-reshaper#42]
there are some fonts with unique way for merging two letters in a row into one letter here is an example:
the letters: "نجـ" the ordinary way to visualize it is:
![image](https://user-images.githubusercontent.com/35382418/85888500-ff7f0980-b7e9-11ea-9b1c-c523e873e0a1.png)
but there is a way used in many fonts that automatically merges any certain two letters in a row like:
the letters: "نجـ" the other cool way to visualize it is:
![image](https://user-images.githubusercontent.com/35382418/85888664-5389ee00-b7ea-11ea-901d-dbd7e8b622dd.png)
and there are too many letters that go into one letter with unique look like this,
for example :
![image](https://user-images.githubusercontent.com/35382418/85888788-8d5af480-b7ea-11ea-8b81-805c66dd6aab.png)

**Comment by mpcabd** [comment]
It's already supported, but disabled by default, you need to enable it in your own config, like `{'ARABIC LIGATURE NOON WITH JEEM': True}` or in your `.ini` file like `ARABIC LIGATURE NOON WITH JEEM = yes`. See the default config [here](https://github.com/mpcabd/python-arabic-reshaper/blob/master/arabic_reshaper/default-config.ini#L181)
