### ISSUE TITLE
problem with english code

### ISSUE THREAD

**Issue by saeid0034** [mpcabd/python-arabic-reshaper#46]
hi thanks for your great work im using arabic reshaper and its work perefect in all of my text
but wen i try to convert this text (i forgot to tell i yse bidi too)
[0.1s]
[2.6s]
ماشین شماره 11کی، درگیر یه تیراندازی شدم. [2.5s]
وضعیت کد 4 هست ولی مظنون از پا دراومده. [3.9s]
تو خیابون 522 هیل جنوبی به یه آمبولانس نیاز هست،کافه برادران بوس.

its move [?.?s] from end of all line to start of line.
[0.1s]
[2.6s]
[2.5s] .ﻡﺪﺷ ﯼﺯﺍﺪﻧﺍﺮﯿﺗ ﻪﯾ ﺮﯿﮔﺭﺩ ،ﯽﮐ11 ﻩﺭﺎﻤﺷ ﻦﯿﺷﺎﻣ
[3.9s] .ﻩﺪﻣﻭﺍﺭﺩ ﺎﭘ ﺯﺍ ﻥﻮﻨﻈﻣ ﯽﻟﻭ ﺖﺴﻫ 4 ﺪﮐ ﺖﯿﻌﺿﻭ

what can i do with this?

**Comment by saeid0034** [comment]
its reshape full line
can i do something to make it only reshape arabic text and dont touch english?

**Comment by mpcabd** [comment]
The reshaper won't affect any non-Arabic characters, your problem is the bidi code, it's not something I can control actually.

However, I can't see the problem you're mentioning, as when the text is mixed with Arabic and non-Arabic characters, bidi is used, and then rendered it all looks good:

![image](https://user-images.githubusercontent.com/644992/87242798-5d3d6380-c430-11ea-8108-5f69d9f0e9b7.png)

**Comment by saeid0034** [comment]
> The reshaper won't affect any non-Arabic characters, your problem is the bidi code, it's not something I can control actually.
> 
> However, I can't see the problem you're mentioning, as when the text is mixed with Arabic and non-Arabic characters, bidi is used, and then rendered it all looks good:
> 
> ![image](https://user-images.githubusercontent.com/644992/87242798-5d3d6380-c430-11ea-8108-5f69d9f0e9b7.png)

thanks for reply
yes your right problem coming from bidi
But fortunately I managed to solve this problem with regex (i just move [?.?s] from start of all the line to end)
but i find other problem
i normally use fold for split my english long line to some smaller line
but when i try to use it with arabic and persian its just make text wrong
you have any idea about this?

**Comment by saeid0034** [comment]
hi my last problem fully solved
but i face new problem with reshaper
i use reshaper on txt file
but my problem is after saving reshaped file all carriage return of all line converted to CRLF 
What can i do about this
