### ISSUE TITLE
[Harakat] Position of Harakat is off. Not able to understand the issue.

### ISSUE THREAD

**Issue by askprateek** [mpcabd/python-arabic-reshaper#51]
![Screenshot 2020-08-09 at 9 50 47 PM](https://user-images.githubusercontent.com/9272830/89736894-7ca8ca00-da8a-11ea-8d2c-40ba209bdd8b.png)

Check the last character,
The sign appears to be connected with the character. Any advice?

**Comment by mpcabd** [comment]
This, I believe is a matter of font and rendering engine, try maybe setting a bigger line height or something similar, the reshaper just reshapes doesn't really render anything.
