### ISSUE TITLE
ResourceWarning: unclosed file in __version__.py

### ISSUE THREAD

**Issue by stephanema** [mpcabd/python-arabic-reshaper#58]
hi,

today I updated `xhtml2pdf` and since this new version depends on `arabic-resharper` I had to install this too.

When starting my app with the python option `-Wd` I get the following warning:

`
C:\python38\lib\site-packages\arabic_reshaper\__init__.py:12: ResourceWarning: unclosed file <_io.TextIOWrapper name='C:\\python38\\lib\\site-packages\\arabic_reshaper\\__version__.py' mode='r' encoding='cp1252'>
  exec(open(os.path.join(os.path.dirname(__file__), '__version__.py')).read())
ResourceWarning: Enable tracemalloc to get the object allocation traceback
`

could you have a quick fix for this ?

Thanks :-)

**Comment by fbernhart** [comment]
@stephanema  Nice to hear, that you're using xhtml2pdf. :) I'm contributing and trying to improve xhtml2pdf at the moment.

I also saw this warning and that's why I've already submitted a PR #57 to arabic-reshaper to solve it.

As soon as it gets merged, there shouldn't be a Warning anymore.
