### ISSUE TITLE
lam-meem ligature

### ISSUE THREAD

**Issue by oneOfThePeople** [mpcabd/python-arabic-reshaper#6]
i try to draw on image lam-meem with font amiri (https://github.com/khaledhosny/amiri-font)
its suppose to see like this: http://www.charbase.com/fccc-unicode-arabic-ligature-lam-with-meem-initial-form
the result look like normal (not like the ligature) when i try to draw "لملم" but when i draw directly the unicode (fccc) its work 
there is way to change this in your code?
thank you

**Comment by mpcabd** [comment]
Hello @oneOfThePeople,

It can be added to the code but I'm afraid not all fonts support this ligature and probably don't have a fallback option, I need to try that maybe first, I'll check and respond back.

Sorry for the late response but I was on vacation 🙂

**Comment by oneOfThePeople** [comment]
i know for sure that not all the font support this ligature... 
this is a [library](https://github.com/davelab6/pyfontaine) for checking if the unicode is in the font
thanks again it's will be very helpful

**Comment by khaledhosny** [comment]
The right way to handle this is to have proper OpenType support, but you can’t do this by manipulating text string as it is the case here.

**Comment by mpcabd** [comment]
Hi @oneOfThePeople,

You can now with version 2.0.0 customise and configure the reshaper to your own preferences, it supports a long list of ligatures, feel free to try it!

**Comment by oneOfThePeople** [comment]
awesome!!!
thank you very much
i will try it right away...
thanks again
