### ISSUE TITLE
Wrong order when English is used inside the text

### ISSUE THREAD

**Issue by puraminy** [mpcabd/python-arabic-reshaper#62]
I want to print a Persian phrase (right to left) in a python console application. It's okay if all chars are in Persian. However, if it's mixed with English (including the ending dot (.), it shows it incorrectly.

Examples:

این خوب است # this is okay
این خوب است. # the dot must be on the left-most side not right (the problem exists even in this editor)

این متن شامل English است.

The last one must be printed as:

.است English این متن شامل 

To type the above, I typed it in the wrong order to show the right order!

===========
I used your package with the same problem.

**Comment by ahmed4end** [comment]
you can split and reorder them in your own i guess, no need to let arabic_reshaper handle them together.

**Comment by mpcabd** [comment]
If you mix Arabic with non-Arabic, the reshaper will ignore the non-Arabic, and will reshape the Arabic ones. If you are using `get_display` to reverse the text, it will also ignore the non-Arabic and will reverse the Arabic ones, see the image below.

<img width="836" alt="Screenshot 2020-12-17 at 12 04 15" src="https://user-images.githubusercontent.com/644992/102480176-32e77600-4060-11eb-9127-e443a662b6ac.png">

The text in the text area is entered into the browser, so no reshaping or whatever, only the browser rendering the text correctly. The text below the text area is using `get_display` over `reshape` to display it correctly. You can test it yourself [here](https://reshaper.mpcabd.xyz/).

Please re-open if it's an issue in the reshaper itself confusing Arabic with non-Arabic characters.
