### ISSUE TITLE
Adding support for Sorani-Kurdish

### ISSUE THREAD

**Issue by ngmanageit** [mpcabd/python-arabic-reshaper#66]
First of all thank you so much for your amazing project.
Is it possible to add support for Sorani-Kurdish?

Thanks

**Comment by ravarage** [comment]
Yes it does, from config set language  to Kurdish, and it will work with kurdish sorani letters, I tested it with sarchia fonts 

This will only work with unicode older ali k font are not support it

**Comment by ngmanageit** [comment]
Thank you!!
