### ISSUE TITLE
'ARABIC LETTER MEEM FINAL FORM' (U+FEE2) (and others) not part of CP864

### ISSUE THREAD

**Issue by miracle2k** [mpcabd/python-arabic-reshaper#7]
I know this isn't related to this library per se, but I wonder if maybe you have any information about this.

I am trying to add Arabic script support to python-escpos. So I tried converting the letters to their presentational forms, and sent them to a POS printer supporting CP864 (among others). This doesn't quite work - the codepage doesn't  include this particular character. Others that are missing: for example 'ARABIC LETTER TEH MEDIAL FORM' (U+FE98).

I was under the impression that CP864 was designed to have separate glyphs for the different forms. I guess not for every form, though.

How would this commonly be handled? (How was this handled in the olden times?) Would I use some custom logic to fall back on an unshaped form if necessary?

**Comment by mpcabd** [comment]
Hi @miracle2k,

I'm not sure how this should be handled really, and if you want for the Arabic text to be properly rendered then you'd have to use all forms, if the font or the rendering engine doesn't support all the forms I guess you won't be able to solve the problem. The only solution would be to actually render the text as an image (SVG/PNG/PostScript) and then send it to the printer and it won't have to render it on its own.

Sorry for not replying before, I seem to have forgotten about this.
Regards.
