### ISSUE TITLE
Gaps between some characters

### ISSUE THREAD

**Issue by raghada** [mpcabd/python-arabic-reshaper#72]
Salam,

I'm trying to render some Arabic sentences using your library along with the the [synthetic text generation package](https://github.com/Belval/TextRecognitionDataGenerator). The problem is that I'm getting Arabic sentences with some gaps between the letters, please see my code and a screenshot below:

```
from arabic_reshaper import ArabicReshaper

configuration = {
    'delete_harakat': True,
    'support_ligatures': True,
    'use_unshaped_instead_of_isolated': True,
}
reshaper = ArabicReshaper(configuration=configuration)
text = u' عام استقلال طهران المملكة العربية السعودية'
reshaped_text = reshaper.reshape(text)
bidi_text = get_display(reshaped_text)
generator = GeneratorFromStrings([bidi_text,],
                                 fonts=["Amiri-Regular.ttf"], size=50, character_spacing=-1)
next(generator)[0]
```

![image](https://user-images.githubusercontent.com/12050966/136920456-01141277-4deb-4384-b603-c43c00c35581.png)

Thanks

**Comment by mpcabd** [comment]
This is purely a rendering problem, try a different font, and maybe a different rendering mechanism.
