### ISSUE TITLE
AttributeError: 'ImageFont' object has no attribute 'getmask2'

### ISSUE THREAD

**Issue by mutairibassam** [mpcabd/python-arabic-reshaper#76]
I was trying to add Arabic text in an image but faced this exception `AttributeError: 'ImageFont' object has no attribute 'getmask2'`. ([Implementation without font](https://user-images.githubusercontent.com/54819958/147732011-e8afc7a6-c30c-4165-b940-9b2cd5db4c12.png))

After investigation, it seems the default font is not handled so a specific font need to be passed. ([Implementation with font](https://user-images.githubusercontent.com/54819958/147732264-a47e169c-cd49-4b69-a2eb-1f8a528ac36f.png))

Why the default font is not handled?

**Comment by mpcabd** [comment]
First, this is definitely not an issue with the reshaper itself 👎 

The problem, as far as I understand, is that the default font is not TrueType, so it won't handle Unicode characters properly. You can investigate further if you like, but in any case, you must always use a font that supports Arabic.
