### ISSUE TITLE
Unnecessary setuptools requirement

### ISSUE THREAD

**Issue by 0-wiz-0** [mpcabd/python-arabic-reshaper#77]
setup.py includes `setuptools` in its `install_requires`.

As far as I can tell, setuptools is not used after installation, so this should be put in `setup_requires` or just removed.

**Comment by 0-wiz-0** [comment]
This is correct after all, it's using pkg_resources.

**Comment by joekohlsdorf** [comment]
Can you reopen the issue please?
`pkg_resources` is imported but not used anywhere.
