### ISSUE TITLE
Yank 2.1.3 because of invalid fonttools version constraint

### ISSUE THREAD

**Issue by tlaferriere** [mpcabd/python-arabic-reshaper#85]
Hi,
Good job on this project, it appears to be quite a foundational project for internationalized display.

Because this a transitive dependency to a project of mine, it happens to break dependency resolution with poetry due to the issue fixed in #79. I would really appreciate if you could yank the 2.1.3 version from pypi and (ideally) release 2.1.4 so that I can remove the constraint from my dependency list. I like to keep only the packages I import directly in my dependency list. (My project depends on xhtml2pdf which depends on this package).

Keep up the good work, if you need any help to get this done, let me know 😉

**Comment by mpcabd** [comment]
Thanks for reminding me of that. 2.1.3 is yanked now, and 2.1.4 is released.
