### ISSUE TITLE
Security vulnerability on the "future" dependency

### ISSUE THREAD

**Issue by Ash-Crow** [mpcabd/python-arabic-reshaper#88]
There is a security vulnerability with high severity on future, which is a dependency of this project.

Per the discussion there https://github.com/PythonCharmers/python-future/issues/612, it seems that the project is more or less dead, and the PR to fix this vulnerability has now been opened for two weeks.

As future only exists to maintain compatibility with python2.7, which itself has been officially EOL'd for 3 years now, perhaps it is the occasion for this project to drop python2 compatibility at all?

**Comment by mpcabd** [comment]
I'll release a new version without the `future` dependency and py2 support. Thanks for flagging this.
